In [1]:
using StaticArrays
# using Plots
using LinearAlgebra
# using Makie
using GLMakie 
using LsqFit
include("Elastic.jl")
using .Elastic
using FFMPEG
using DelimitedFiles
using Distributions
using Statistics
using Plots
atom_positions = [
    Vector([0.0, 0.0, 0.0]),
    Vector([0.0, 0.5, 0.5]),
    Vector([0.5, 0.0, 0.5]),
    Vector([0.5, 0.5, 0.0]),
    Vector([1.0, 0.0, 0.0]),
    Vector([0.0, 1.0, 0.0]),
    Vector([0.0, 0.0, 1.0]),
    Vector([0.5, 1.0, 0.5]),
    Vector([1.0, 0.5, 0.5]),
    Vector([0.5, 0.5, 1.0]),
    Vector([1.0, 0.0, 1.0]),
    Vector([1.0, 1.0, 0.0]),
    Vector([0.0, 1.0, 1.0]),
    Vector([1.0, 1.0, 1.0])
] 


lattice_constant = 3.61
# 定义铜的FCC晶胞的基矢量
lattice_vectors = collect((Matrix([
    lattice_constant 0.0 0.0; #a1
    0.0 lattice_constant 0.0; #a2
    0.0 0.0 lattice_constant] #a3
))')

# 创建铜的原子列表
atoms = [Atom(pos) for pos in atom_positions]

14-element Vector{Atom}:
 Atom([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.0, 0.5, 0.5], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.5, 0.0, 0.5], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.5, 0.5, 0.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([1.0, 0.0, 0.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.0, 1.0, 0.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.0, 0.0, 1.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.5, 1.0, 0.5], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([1.0, 0.5, 0.5], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.5, 0.5, 1.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([1.0, 0.0, 1.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([1.0, 1.0, 0.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([0.0, 1.0, 1.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])
 Atom([1.0, 1.0, 1.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0])

In [69]:
cell=UnitCell(lattice_vectors,atoms)
cpcell=copycell(cell,6,6,6)
fcell=filtercell(cpcell)

UnitCell([3.61 0.0 0.0; 0.0 3.61 0.0; 0.0 0.0 3.61], Atom[Atom([0.0, 0.0, 0.0], [0.0, 0.0, 0.0], 1.0, 8, [1, 1, 1]), Atom([0.0, 0.0, 1.0], [0.0, 0.0, 0.0], 1.0, 4, [1, 1, 0]), Atom([0.0, 0.0, 2.0], [0.0, 0.0, 0.0], 1.0, 4, [1, 1, 0]), Atom([0.0, 0.0, 3.0], [0.0, 0.0, 0.0], 1.0, 4, [1, 1, 0]), Atom([0.0, 0.0, 4.0], [0.0, 0.0, 0.0], 1.0, 4, [1, 1, 0]), Atom([0.0, 0.0, 5.0], [0.0, 0.0, 0.0], 1.0, 4, [1, 1, 0]), Atom([0.0, 1.0, 0.0], [0.0, 0.0, 0.0], 1.0, 4, [1, 0, 1]), Atom([0.0, 1.0, 1.0], [0.0, 0.0, 0.0], 1.0, 2, [1, 0, 0]), Atom([0.0, 1.0, 2.0], [0.0, 0.0, 0.0], 1.0, 2, [1, 0, 0]), Atom([0.0, 1.0, 3.0], [0.0, 0.0, 0.0], 1.0, 2, [1, 0, 0])  …  Atom([5.5, 4.5, 2.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0]), Atom([5.5, 4.5, 3.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0]), Atom([5.5, 4.5, 4.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0]), Atom([5.5, 4.5, 5.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 0]), Atom([5.5, 5.5, 0.0], [0.0, 0.0, 0.0], 1.0, 2, [0, 0, 1]), Atom([5.5, 5.5, 1.0], [0.0, 0.0, 0.0], 1.0, 1, [0, 0, 

In [70]:
##Cu:
beta0=3.83
beta1=2.2
beta2=6.0
beta3=2.2
t1=2.72
t2=3.04
t3=1.95 
B=1.420 #eV
A=0.94
Ec=3.54
Re=2.555

2.555

In [71]:
function  rhoa(R::Float64,beta::Float64,Re::Float64)
    return exp(-beta*(R/Re-1))
end

rhoa (generic function with 1 method)

In [72]:
function rho0(cell::UnitCell,i::Int,beta0::Float64=beta0,Re::Float64=Re;rc::Float64=10.0)
natom=length(cell.atoms)
ltv=cell.lattice_vectors
re=0.0
for j=1:natom
    if i!=j
        nrij=norm(ltv*(cell.atoms[j].position-cell.atoms[i].position))
        if nrij<rc
            re+=rhoa(nrij,beta0,Re)
            # println("nrij=$nrij,i:$i,j:$j")
        end
    end
end
return re
end

rho0 (generic function with 3 methods)

In [73]:
function rho1sq(cell::UnitCell,i::Int,beta1::Float64=beta1,Re::Float64=Re;rc::Float64=10.0)
natom=length(cell.atoms)
ltv=cell.lattice_vectors
ree=0.0
for a in 1:3
re=0.0
 for j in 1:natom
    if i!=j
        rij=(ltv*(cell.atoms[j].position-cell.atoms[i].position))
        nrij=norm(rij)
        if nrij<rc
            re+=rhoa(norm(rij),beta1,Re)*rij[a]/nrij
        end
    end
 end
ree+=re^2
end
return ree
end

rho1sq (generic function with 3 methods)

In [74]:
function rho2sq(cell::UnitCell,i::Int,beta2::Float64=beta2,Re::Float64=Re;rc::Float64=10.0)
natom=length(cell.atoms)
ltv=cell.lattice_vectors
ree=0.0
re2=0.0
    for a in 1:3
        for b in 1:3
            re=0.0
            for j in 1:natom
                if i!=j
                    rij=(ltv*(cell.atoms[j].position-cell.atoms[i].position))
                    nrij=norm(rij)
                    if nrij<rc
                        re+=rhoa(nrij,beta2,Re)*rij[a]*rij[b]/nrij^2
                    end

                    # if a==1&&b==1&&(nrij<rc)
                    #     re2+=rhoa(nrij,beta2,Re)
                    # end

                end
            end
            ree+=re^2
        end
    end
    return ree-(re2^2)/3
end

rho2sq (generic function with 3 methods)

In [75]:
function rho3sq(cell::UnitCell,i::Int,beta3::Float64=beta3,Re::Float64=Re;rc::Float64=10.0)

natom=length(cell.atoms)
ltv=cell.lattice_vectors
reaa=0.0
re=0.0
for c=1:3
    for b=1:3
        for a=1:3
            ree=0.0
            rea=0.0
            for j in 1:natom
                if i!=j
                    rij=(ltv*(cell.atoms[j].position-cell.atoms[i].position))
                    nrij=norm(rij)
                    if nrij<rc
                        ree+=rhoa(nrij,beta3,Re)*rij[a]*rij[b]*rij[c]/nrij^3

                        if b==1&&c==1&&(nrij<rc)
                            rea+=rhoa(nrij,beta3,Re)*rij[a]/nrij
                        end
                    end
                end
            end
            if b==1&&c==1
                reaa+=rea^2
            end
            re+=ree^2
        end
    end

end
return re-reaa*0.6
end

rho3sq (generic function with 3 methods)

In [76]:
function gammai(cell::UnitCell,i::Int,t::Vector{Float64}=[t1,t2,t3],beta::Vector{Float64}=[beta0,beta1,beta2,beta3],Re::Float64=Re;rc::Float64=10.0)
    g=0.0
  
    g=t[1]*(rho1sq(cell,i,beta[2],Re,rc=rc))+t[2]*(rho2sq(cell,i,beta[3],Re,rc=rc))+t[3]*(rho3sq(cell,i,beta[4],Re,rc=rc))
 
   
    return g/rho0(cell,i,beta[1],Re,rc=rc)^2
end

gammai (generic function with 4 methods)

In [77]:
function rhoi(cell::UnitCell,i::Int,t::Vector{Float64}=[t1,t2,t3],beta::Vector{Float64}=[beta0,beta1,beta2,beta3],Re::Float64=Re;rc::Float64=10.0)
    return rho0(cell,i,beta[1],Re,rc=rc)*2/(1+exp(-gammai(cell,i,t,beta,Re,rc=rc))) 
end

rhoi (generic function with 4 methods)

In [78]:
function drhoa(R::Vector{Float64},beta::Float64,Re::Float64)
    nR=norm(R)
    return (rhoa(nR,beta,Re)/nR*beta/Re)*R
end

drhoa (generic function with 1 method)

In [79]:
function drho0(cell::UnitCell,i::Int,beta0::Float64=beta0,Re::Float64=Re; rc::Float64=10.0)
natom=length(cell.atoms)
ltv=cell.lattice_vectors
re=zeros(3)
for j=1:natom
    if i!=j
        rij=ltv*(cell.atoms[j].position-cell.atoms[i].position)
        nrij=norm(rij)
        if nrij<rc
            # re-=(beta0*rhoa(nrij,beta0,Re)/nrij/Re)*rij
            re+=drhoa(rij,beta0,Re)
        end
    end
end
return re
end

drho0 (generic function with 3 methods)

In [80]:
function drho1sq(cell::UnitCell,i::Int,beta1::Float64=beta1,Re::Float64=Re;rc::Float64=10.0)
    natom=length(cell.atoms)
    ltv=cell.lattice_vectors
    ree=zeros(3)
    for a in 1:3
    re1=zeros(3)
    re2=0.0
     for j in 1:natom
        if i!=j
            rij=(ltv*(cell.atoms[j].position-cell.atoms[i].position))
            nrij=norm(rij)
            if nrij<rc
                rhoaj=rhoa(nrij,beta1,Re)
                drhoaj=drhoa(rij,beta1,Re)
                re1+=(rij[a]*(1/nrij^3*rhoaj*rij+drhoaj/nrij)-I(3)[a,:]*rhoaj/nrij)
                re2+=rhoaj*rij[a]/nrij
            end
        end
     end
    ree+=2*re1*re2
    end
    return ree
    end

drho1sq (generic function with 3 methods)

In [81]:

drho1sq(fcell,4)

3-element Vector{Float64}:
 13.65946365416106
 13.659463654161062
 -7.354352270360075e-16

In [82]:
function drho2sq(cell::UnitCell,i::Int,beta2::Float64=beta2,Re::Float64=Re;rc::Float64=10.0)
    natom=length(cell.atoms)
    ltv=cell.lattice_vectors
    ree1=zeros(3)
    re2=zeros(3)
    re20=0.0
    
        for a in 1:3
            for b in 1:3
                re1=zeros(3)
                re10=0.0
                
                for j in 1:natom
                    if i!=j
                        rij=(ltv*(cell.atoms[j].position-cell.atoms[i].position))
                        nrij=norm(rij)
                        rhoaj=rhoa(nrij,beta2,Re)
                        drhoaj=drhoa(rij,beta2,Re)
                        if nrij<rc
                            re1+=(rij[a]*rij[b]*(2*rij/nrij^4*rhoaj+drhoaj/nrij^2))-(I(3)[a,:]*rij[b]+I(3)[b,:]*rij[a])*rhoaj/nrij^2
                            re10+=rhoaj*rij[a]*rij[b]/nrij^2

                        end
    
                        # if a==1&&b==1&&(nrij<rc)
                        #     re2+=drhoaj
                        #     re20+=rhoaj
                        # end
    
                    end
                end
                ree1+=re10*re1
            end
        end
        return 2*(ree1-1/3*re20*re2)
    end

drho2sq (generic function with 3 methods)

In [83]:
function drho3sq(cell::UnitCell,i::Int,beta3::Float64=beta3,Re::Float64=Re;rc::Float64=10.0)

    natom=length(cell.atoms)
    ltv=cell.lattice_vectors

    ree1=zeros(3)
    ree2=zeros(3)
    for c=1:3
        for b=1:3
            for a=1:3
                re1=zeros(3)
                re10=0.0
                re2=zeros(3)
                re20=0.0
                for j in 1:natom
                    if i!=j
                        rij=(ltv*(cell.atoms[j].position-cell.atoms[i].position))
                        nrij=norm(rij)
                        if nrij<rc
                            rhoaj=rhoa(nrij,beta3,Re)
                            drhoaj=drhoa(rij,beta3,Re)
                            re1+=(rij[a]*rij[b]*rij[c]*(3*rij/nrij^5*rhoaj+drhoaj/nrij^3))-(I(3)[a,:]*rij[b]*rij[c]+I(3)[b,:]*rij[a]*rij[c]+I(3)[c,:]*rij[a]*rij[b])*rhoaj/nrij^3
                            re10+=rhoaj*rij[a]*rij[b]*rij[c]/nrij^3

                            if b==1&&c==1
                                re2+=rij[a]*(drhoaj/nrij+rhoaj*rij/nrij^3)-I(3)[a,:]*rhoaj/nrij
                                re20+=rhoaj*rij[a]/nrij
                                
                            end
                        end
                    end
                end
                if b==1&&c==1
                    ree2+=2*re2*re20
                end
                ree1+=2*re10*re1
            end
        end
    
    end
    return ree1-ree2*0.6
    end

drho3sq (generic function with 3 methods)

In [84]:
function  Ngradiant(cell::UnitCell,i::Int,f::Function,para::Vector,dr::Vector{Float64}=[-0.001,-0.01,0.001])
    df=zeros(3)
    lt=cell.lattice_vectors
    invlt=inv(lt)
    drm=Diagonal(dr)
    

    for j in 1:3
        dri=invlt*drm[j,:]
        dcell=deepcopy(cell)
        dcell.atoms[i].position+=dri
        f1=f(dcell,i,para...)
        dcell.atoms[i].position-=2*dri
        f2=f(dcell,i,para...)
       
        df[j]=(f1-f2)/2/dr[j]

    end

    return df
end

Ngradiant (generic function with 2 methods)

In [85]:
function dgammai(cell::UnitCell,i::Int,t::Vector{Float64}=[t1,t2,t3],beta::Vector{Float64}=[beta0,beta1,beta2,beta3],Re::Float64=Re;rc::Float64=10.0)
    dg=zeros(3)
  
    rho1sqi=rho1sq(cell,i,beta[2],Re,rc=rc)
    rho2sqi=rho2sq(cell,i,beta[3],Re,rc=rc)
    rho3sqi=rho3sq(cell,i,beta[4],Re,rc=rc)
    rho0i=rho0(cell,i,beta[1],Re,rc=rc)
    drho1sqi=drho1sq(cell,i,beta[2],Re,rc=rc)
    drho2sqi=drho2sq(cell,i,beta[3],Re,rc=rc)
    drho3sqi=drho3sq(cell,i,beta[4],Re,rc=rc)
    drho0i=drho0(cell,i,beta[1],Re,rc=rc)
    dg+=t[1]*(drho1sqi*(rho0i)-2*rho1sqi*drho0i)/rho0i^3
    dg+=t[2]*(drho2sqi*(rho0i)-2*rho2sqi*drho0i)/rho0i^3
    dg+=t[3]*(drho3sqi*(rho0i)-2*rho3sqi*drho0i)/rho0i^3
    return dg
end

dgammai (generic function with 4 methods)

In [86]:
function drhoi(cell::UnitCell,i::Int,t::Vector{Float64}=[t1,t2,t3],beta::Vector{Float64}=[beta0,beta1,beta2,beta3],Re::Float64=Re;rc::Float64=10.0)
    rho0i=rho0(cell,i,beta[1],Re,rc=rc)
    gi=gammai(cell,i,t,beta,Re,rc=rc)
    dg=dgammai(cell,i,t,beta,Re,rc=rc)
    drho0i=drho0(cell,i,beta[1],Re,rc=rc)
    dr=2*drho0i/(1+exp(-gi))+2*rho0i/(1+exp(-gi))^2*exp(-gi)*dg
    return dr
end

drhoi (generic function with 4 methods)

In [87]:
drhoi(fcell,4)

3-element Vector{Float64}:
  6.7812078549430534
  6.7812078549430534
 -1.443900473042316e-16

In [88]:
Ngrad=Ngradiant(fcell,4,rhoi,[],[0.001,0.01,0.001])

3-element Vector{Float64}:
 6.781208814021333
 6.78130376019217
 0.0

In [89]:
function Frho(cell::UnitCell,i::Int,t::Vector{Float64}=[t1,t2,t3],beta::Vector{Float64}=[beta0,beta1,beta2,beta3],Re::Float64=Re,Ec::Float64=Ec,A::Float64=A;rc::Float64=10.0)
    k=rhoi(cell,i,t,beta,Re,rc=rc)/rho0(cell,i,beta[1],Re,rc=rc)
    return A*Ec*(k)*log(k)
end

Frho (generic function with 12 methods)

In [90]:
function dFrho(cell::UnitCell,i::Int,t::Vector{Float64}=[t1,t2,t3],beta::Vector{Float64}=[beta0,beta1,beta2,beta3],Re::Float64=Re,Ec::Float64=Ec,A::Float64=A;rc::Float64=10.0)

    dri=drhoi(cell,i,t,beta,Re,rc=rc)
    r0i=rho0(cell,i,beta[1],Re,rc=rc)
    ri=rhoi(cell,i,t,beta,Re,rc=rc)
    dr0i=drho0(cell,i,beta[1],Re,rc=rc)
    k=ri/r0i
 dF=A*Ec*(1+log(k))*(dri/r0i-ri/r0i^2*dr0i)
    return dF
end

dFrho (generic function with 12 methods)

In [91]:
@time [dFrho(fcell,i) for i in 1:length(fcell.atoms)]

 14.099232 seconds (407.57 M allocations: 29.812 GiB, 12.54% gc time, 0.39% compilation time)


864-element Vector{Vector{Float64}}:
 [-0.1977485488458781, -0.1977485488458781, -0.1977485488458781]
 [-0.6312988641487154, -0.6312988641487177, 0.04463079838776343]
 [-0.6331758226368831, -0.6331758226368819, 0.0017368528825428351]
 [-0.6332479107101061, -0.6332479107101049, -1.4636635566574282e-18]
 [-0.633054600809335, -0.6330546008093337, -0.011104886000668546]
 [-0.6010995092926493, -0.6010995092926481, 0.00015190603033164772]
 [-0.6312988641487165, 0.04463079838776332, -0.6312988641487177]
 [-0.7329830871856066, 0.06308612183988424, 0.06308612183988427]
 [-0.7709213587799546, 0.06487465953747458, 0.002973158943020395]
 [-0.7722889697070459, 0.06481962982666083, -2.0112872433475442e-17]
 ⋮
 [0.7722889697070416, -0.06481962982666112, -3.7568575102786533e-17]
 [0.7634969348289078, -0.06469516823951031, -0.017848805355724133]
 [0.654816253062581, -0.059645444058044894, -0.052037333840494054]
 [0.1977485488458781, 0.1977485488458781, -0.1977485488458781]
 [0.6312988641487177, 0.63129

In [93]:
@time [Ngradiant(fcell,i,Frho,[]) for i in 1:length(fcell.atoms)]

 17.771251 seconds (384.87 M allocations: 28.707 GiB, 11.91% gc time, 0.10% compilation time)


864-element Vector{Vector{Float64}}:
 [-0.19774839467645577, -0.19773313267306136, -0.19774839467645577]
 [-0.6312983480154521, -0.6312472528149371, 0.04463075100735736]
 [-0.6331753035655474, -0.6331239175271897, 0.0017368514204640917]
 [-0.6332473914594239, -0.6331959876272553, 0.0]
 [-0.6330540823324959, -0.6330027552160722, -0.011104875910827872]
 [-0.6010989947409229, -0.6010480562849363, 0.00015202268066616398]
 [-0.6312983480150081, 0.04462606039354888, -0.6312983480150081]
 [-0.7329827612787554, 0.06307947849146789, 0.06308605540383816]
 [-0.7709210170749881, 0.06486790839381751, 0.0029731566877355675]
 [-0.7722886273804352, 0.06481288502322435, 0.0]
 ⋮
 [0.7722886273826557, -0.06481288502315774, 0.0]
 [0.7634965966156759, -0.06468842526805574, -0.01784879057331601]
 [0.6548159345867166, -0.059638770423298126, -0.05203712351553591]
 [0.1977483946755676, 0.19773313267315018, -0.19774839467645577]
 [0.6312983480154521, 0.6312472528150259, 0.04463075100602509]
 [0.6331753035664356